# Generated by Django 2.1.5 on 2019-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kyykka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='throw',
            name='throw_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='throw_turn',
            field=models.IntegerField(),
        ),
    ]
