# Generated by Django 2.1.5 on 2019-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kyykka', '0003_auto_20190324_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='score_first',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_fourth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_second',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_third',
            field=models.IntegerField(null=True),
        ),
    ]
