# Generated by Django 2.1.5 on 2019-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kyykka', '0006_auto_20190328_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_first_round_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_second_round_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_first_round_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_second_round_score',
            field=models.IntegerField(blank=True),
        ),
    ]
