# Generated by Django 2.2.8 on 2020-01-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0010_auto_20200107_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='teams',
        ),
        migrations.AddField(
            model_name='match',
            name='field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
