# Generated by Django 2.2.8 on 2020-01-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0011_auto_20200112_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='score_first',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_fourth',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_second',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='throw',
            name='score_third',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
