# Generated by Django 2.2.8 on 2020-03-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyykka', '0012_auto_20200114_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='post_season',
            field=models.BooleanField(default=False),
        ),
    ]
